### PR TITLE
feat: update to laminas coding standart v2

### PR DESCRIPTION
**Pull request by alexraputa**
|    Q          |   A
|-------------- | ------
| QA            | yes

### CODE REVIEW

**Comment by boesing** [comment]
I've tried to rebase but I dont want to break your commit message (DCO, signing and stuff).

When you rebase this, put this into the `phpcs.xml` before executing `cs-fix`:

```
<rule ref="LaminasCodingStandard">
    <exclude name="WebimpressCodingStandard.Namespaces.UnusedUseStatement"/>
    <exclude name="WebimpressCodingStandard.Commenting.TagWithType.InvalidTypeFormat"/>
    <exclude name="WebimpressCodingStandard.Commenting.TagWithType.InvalidParamName"/>
</rule>
```
I've addressed these bugs in webimpress/coding-standard#124 and webimpress/coding-standard#125

**Comment by alexraputa** [comment]
> I've tried to rebase but I dont want to break your commit message (DCO, signing and stuff).
> 
> When you rebase this, put this into the `phpcs.xml` before executing `cs-fix`:
> 
> ```
> <rule ref="LaminasCodingStandard">
>     <exclude name="WebimpressCodingStandard.Namespaces.UnusedUseStatement"/>
>     <exclude name="WebimpressCodingStandard.Commenting.TagWithType.InvalidTypeFormat"/>
>     <exclude name="WebimpressCodingStandard.Commenting.TagWithType.InvalidParamName"/>
> </rule>
> ```
> 
> I've addressed these bugs in [webimpress/coding-standard#124](https://github.com/webimpress/coding-standard/issues/124) and [webimpress/coding-standard#125](https://github.com/webimpress/coding-standard/issues/125)

I'll try, thx you.

**Comment by alexraputa** [comment]
@boesing, ready for review. 🔍

**Review by boesing — APPROVED** [review]
LGTM 🎉

**Pull request merged**
